### ISSUE TITLE
Garbage Collection Behavior

### ISSUE THREAD

**Issue by xLinkKnight** [Rappsilber-Laboratory/XiSearch#115]
An issues occurs when memory utilization reaches the set limit. xiSEARCH version 1.8.6.

<img width="297" alt="Warning" src="https://github.com/user-attachments/assets/98831af0-9956-42e3-8181-b6befe0b731f">

A warning which indicates a potential out-of-memory situation (memory is misspelled). Is there a way to silence the warning? I haven't noticed this warning since upgrading to the latest major version of Java and xiSEARCH. I've manually set the watchdog limit in excess of 50,000 minutes and increased the allotted RAM to near max (740 GB). 

Once the warning is accepted, the search progress continues. Or does the search task still progress in the background? The log freezes until you accept the warning.

**Comment by grandrea** [comment]
how large is your fasta database?

**Comment by lutzfischer** [comment]
It is just a warning and unless you stop the search it should just continue. 
It get raised when more then 50% of the time is used for garbage collection - but it is only a warning and part of the "problem" here could just be that you give it more memory then I actually tested that function with. In java garbage collection can and will run in parallel to the actual process. That would not actually affect your search at all. But if you have a lot of memory that garbage collection can become time consuming simply because it keeps "garbage" around for longer and then has to clean up a lot more in one go - which then takes more time at fewer time points. ANd maybe that is exactly what you see. So unless you noticed that no progress is made then I would guess it is just "to much memory" and I need to think of a way to handle that.

**Comment by lutzfischer** [comment]
If an actual out of memory situation happens it will raise a different message.

**Comment by lutzfischer** [comment]
The search is running actually in a separate process - and the gui is just reading the output form that process + some status info. So the search is not stopped/paused - only the gui.
