### ISSUE TITLE
BS3 configuration

### ISSUE THREAD

**Issue by ThomasGossenreiter** [Rappsilber-Laboratory/XiSearch#48]
Dear xisearch team,

I would like to define BS3 as cross-linker from prot.nterm and K to prot.nterm, K, S, T, Y and also to search for hydrolyzed and trsi quenched mono-links and loop-links. I tried to define it as following:

crosslinker:AsymetricSingleAminoAcidRestrictedCrossLinker:Name:BS3_asymetric;MASS:138.06807;FIRSTLINKEDAMINOACIDS:K,nterm;SECONDLINKEDAMINOACIDS:K,S,Y,T,nterm;MODIFICATIONS:bs3h2o,18.0105647,bs3tris,121.073903,LOOP,0

However I do not find mono-links at all, neither bs3h2o nor bs3tris, nor loop-links. Could you help me to configure it correctly?

Best regards,
Thomas

**Comment by lutzfischer** [comment]
Ah the problem here is that the cross-linker modifications can not be represented like this for asymeteric cross-linker at the moment (would need to combine it with the site of the cross-linker and don't have that functionality at the moment).

So you need to define them as `variable` or `linear` modifications.
```
modification:variable::SYMBOLEXT:bs3h2o;MODIFIED:K,S,T,Y;DELTAMASS:156.0786347
modification:variable::SYMBOLEXT:bs3tris;MODIFIED:K,S,T,Y;DELTAMASS:259.141973
```
or
```
modification:linear::SYMBOLEXT:bs3h2o;MODIFIED:K,S,T,Y;DELTAMASS:156.0786347
modification:linear::SYMBOLEXT:bs3tris;MODIFIED:K,S,T,Y;DELTAMASS:259.141973
```
(i did not check the tris mass)

The second one will only be applied as part of a linear peptide match while the first can be on linear and cross-linked matches (i.e. simple form of higher order cross-links)

**Comment by ThomasGossenreiter** [comment]
Hey thanks for your help! really appreciate that.

I tried the first option an it works. However, I would also include mono-links on protein N-termini. I tried this:

**modification:variable::SYMBOLEXT:bs3h2o;MODIFIED:nterm,K,S,T,Y;DELTAMASS:156.0786347**

but the search does not start. If I use it without "nterm", it works.

**Comment by lutzfischer** [comment]
for protein n- or c-terminal modifications you need to add an aditional modification:
```
modification:variable::SYMBOLEXT:bs3h2o;MODIFIED:*;DELTAMASS:156.0786347;PROTEINPOSITION:nterm
```
that defines a modification on any amino-acids (`MODIFIED:*`) if they are at the protein n-terminal (`PROTEINPOSITION:nterm`)

**Comment by ThomasGossenreiter** [comment]
Great this works. Thank you very much!

**Comment by lutzfischer** [comment]
I added a description of terminal modifications to the [githup-wiki](https://github.com/Rappsilber-Laboratory/XiSearch/wiki/MiniWiki)
