### ISSUE TITLE
Search for linear modification

### ISSUE THREAD

**Issue by cxdummies** [Rappsilber-Laboratory/XiSearch#85]
Dear Lutz

If I understood correctly, in the default setting, the following line defines the search for BS3amidated linear peptide

modification:linear::SYMBOLEXT:bs3nh;MODIFIED:K,S,T,Y;DELTAMASS:155.094619105

In the defaut BS3 crosslinker setting, there is also the MODIFICATIONS:NH2,17.026549105

From which one of these two does xiSEARCH use to find the linear modification? Does one take precedence over the other? If BS3 is quenched by an amine-based reagent other than ammonia, e.g. Tris, where should the modifiation be defined to find the corresponding monolinks?

In the Linear Peitides result table from a search using the default BS3 setting, one can find both bs3nh and bs3nh2 in the peptide sequences. bs3nh2 is not in the search setting. Could you explain what it is and why it shows up in the sequences?

Many thanks!

**Comment by grandrea** [comment]
Hey,

As far as I know, those are additive i.e. you are defining a modification on linear peptides only called bs3nh with a deltamass of 155.094619105 AND a modification on all peptides with an NH2 group that has a mass of crosslinker mass+17.026549105. The priority will be given to the one that matches better (but here @lutzfischer is the one that should answer!). 

If you want to simplify the search, use only

    modification:linear::SYMBOLEXT:bs3nh;MODIFIED:K,S,T,Y;DELTAMASS:155.094619105

and remove the MODIFICATIONS lines from the BS3 defitinition. 

If instead you want to consider more possibilities (mods on both linear and crosslinked peptides), use only

   modification:variable::SYMBOLEXT:bs3nh;MODIFIED:K,S,T,Y;DELTAMASS:155.094619105
   
What you are referring to is the fact that the same syntax can be put inside the crosslinker definition instead (https://github.com/Rappsilber-Laboratory/XiSearch#crosslinker-settings)
Here with modifications on linear peptides only

    crosslinker:SymetricSingleAminoAcidRestrictedCrossLinker:Name:BS3;MASS:138.06807;LINKEDAMINOACIDS:K(0),S(0.2),T(0.2),Y(0.2),nterm(0);LINEARMODIFICATIONS:NH2,17.026549105
     
here with modifications on all peptides

      crosslinker:SymetricSingleAminoAcidRestrictedCrossLinker:Name:BS3;MASS:138.06807;LINKEDAMINOACIDS:K(0),S(0.2),T(0.2),Y(0.2),nterm(0);MODIFICATIONS:NH2,17.026549105
     
     
to define Tris as the quencher, you can define a modification for it, again as a separate modification or inside the crosslinker definition (please double check the bs3-tris mass!!)

    modification:linear::SYMBOLEXT:bs3tris;MODIFIED:K,S,T,Y;DELTAMASS:259.141973

or

    modification:variable::SYMBOLEXT:bs3tris;MODIFIED:K,S,T,Y;DELTAMASS:259.141973
    
And the same definitions can be given inside the crosslinker as well with the same syntax as above.

**Comment by grandrea** [comment]
Hello,

No problem- sorry I was not clear enough, it is a bit confusing in its flexibility. There are 2 kinds of modifications: variable and linear. "Variable" searches for the modification on all peptides, "Linear" only on linear peptides.

You can encode these modifications 2 ways:
1. in a line defining a modification
2. inside the crosslinker definition

If you are encoding a linear modification with 1) indeed what you write:

    modification:linear::SYMBOLEXT:bs3loop;MODIFIED:K,S,T,Y,nterm;DELTAMASS:138.06807
 
 is correct. The deltamass is the mass change relative to the original amino acid. Then the crosslinker definition should look like this 

    crosslinker:SymetricSingleAminoAcidRestrictedCrossLinker:Name:BS3;MASS:138.06807;LINKEDAMINOACIDS:K(0),S(0.2),T(0.2),Y(0.2),nterm(0)

I.e. not include the modification inside the crosslinker, as they are defined separately.

If *instead* you use 2), then you should not have the separate line that says modification:linear and so on, but rather

    crosslinker:SymetricSingleAminoAcidRestrictedCrossLinker:Name:BS3;MASS:138.06807;LINKEDAMINOACIDS:K(0),S(0.2),T(0.2),Y(0.2),nterm(0);LINEARMODIFICATIONS:NH2,17.026549105,loop,0

In this case, the modification mass is the mass to change the crosslinker by- hence a loop link is 0 (a loop link has the same mass as a crosslink) and an nh2 group is 17.02654915. this is what defines the bs3nh2 that was not in your search.


Whether you want a linear or a variable modification in 1) is defined by the choice of 

    modification:linear
or 
       modification:variable

In 2) it is defined by using the word

    MODIFICATIONS

or

    LINEARMODIFICATIONS
    
Back to your original question- you defined the modification twice (once as a separate line and once in the crosslinker) and xiSEARCH was assigning both, also because they were defined with slightly different masses. Simply choose one and you're good to go.

**Comment by grandrea** [comment]
"nterm" is protein N terminus

**Comment by grandrea** [comment]
could you attach it as a text file (just change the extension to .txt) so that it doesn't take the markdown formatting

**Comment by grandrea** [comment]
We could reproduce the bug whenever "nterm" is in the definition of the modification. The workaround of defining the n-terminal modification separately as above seems to solve the issue

**Comment by grandrea** [comment]
It's hard to know, that depends on the number of proteins in your database. I would start with default values and see what memory and search times come out. If your database is small, rather than increasing MAX_MODIFICATION_PER_PEPTIDE, I would increase MAX_PEPTIDES_PER_PEPTIDE to for example 100, if your memory and search time allows for it. Half those mods can only occur on n-terminal peptides, so i don't think number of modifications per peptide is what is limiting you.

**Comment by grandrea** [comment]
as an aside- we strongly recommend searching with multiple crosslinker and including noncovalent associations in the search

**Comment by grandrea** [comment]
No- I mean to select "multiple crosslinkers" in the GUI and select the crosslinker you used and "NonCovalent" which handles non-covalent association of peptides in the gas phase. This helps removing false positive identifications. https://github.com/Rappsilber-Laboratory/xisearch#crosslinker-selection This defines an additional crosslinker with mass 0 called "NonCovalent" (see the end of this section https://github.com/Rappsilber-Laboratory/xisearch#crosslinker-selection on how to add it to the config file).

Publication: https://pubs.acs.org/doi/10.1021/acs.analchem.8b04037 (see fig.5 for an example of why this is useful to add).

**Comment by grandrea** [comment]
> If I may ask again, with "NonCovalent" added, I saw an extra table "NAPS". Have these PSMs been automatically excluded from the result of the Links table?

You mean after the FDR step? the NAPS table reports noncovalently associated peptides and the links table your crosslinks. If you open the links table in excel, you will see the "crosslinker" column and check that no "NonCovalent" are there. MzIdentML will contain both reporting which psm is which, and xiview.org will show only crosslinkers that aren't from noncovalent association.



> I'm afraid I've encountered another problem. If I included crosslinker:NonCovalentBound:Name:NonCovalent additionally, the search crashed with the following error:
> 
> Search Crashed:null Peptides:DDDDK, DDDDK
> 
> What might be the problem?

at what stage of the search? could you paste more of the log? Have you tried rerunning allocating more memory if possible?

**Comment by grandrea** [comment]
and the search runs otherwise through to the end without the NonCovalent line? Could you attach your current config file? Apologies for the many questions, just trying to understand.

**Comment by lutzfischer** [comment]
can you post the full log - or email it to me? From what you send, a error occurred somewhere and as a result xisearch stopped the search. Just that the actual error is not in the part of the log you posted - need to see why that is the case - 
the `null` in 

INFO: Search Crashed:null Peptides:DDDDK, DDDDK

should have been the error reported again. I hope in the full log there is somewhere the actual error.

**Comment by grandrea** [comment]
hello,
Could you repeat your search with .mgf files insead of .apl?  Apl files also provide spectra with unknown precursor charge state. Could be that that is part of the problem

**Comment by lutzfischer** [comment]
I am not aware that there is any official reason given for that behaviour. 

But the reason for more NAPs in QE products MIGHT be down to how the ions get forwarded into the machine. The "lens" (is named somewhat differently in different machines) is different and might lead to peptides not as easily (in relative terms) disassociate for QE than in others. But that is only an very untested hypothesis. When we looked at crosslink identifications from an early qexactive instrument  - without considering non-covalent peptides at the time - we had an surprising number of overlength and in fact made us in turn aware of the problem of non-covalent associated peptides.
